name: retracer_app

on:
  issues:
    types: [ edited, labeled ]

env:
  INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  ParseCrashLog:
    if: contains(github.event.issue.labels.*.name, 'crash')
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: "stable"

      # prepare debug symbols and crash mini dump
      - name: PrepareSymbol
        id: prepare_symbol
        working-directory: retracer_app
        run: |
          dart pub get
          dart run retracer_app "${{ github.event.issue.body }}"

      - name: DumpCrashLog
        id: dump_crash_log
        run: |
          ./breakpad/linux/x86_64/minidump_stackwalk "${{ steps.prepare_symbol.outputs.mini_dump_file }}" "${{ steps.prepare_symbol.outputs.symbol_directory }}" > crash.log
          crash_log=$(cat crash.log)
          crash_log="${crash_log//'%'/'%25'}"
          crash_log="${crash_log//$'\n'/'%0A'}"
          crash_log="${crash_log//$'\r'/'%0D'}" 
          echo "::set-output name=crash_log::$crash_log"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Crash log dumped

      - name: save comment to file
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const comment_body = "crash log dumped:\n\nmini dump file: `${{ steps.prepare_symbol.outputs.mini_dump_file }}`\n\nback trace:\n\n```\n${{ steps.dump_crash_log.outputs.crash_log }}\n```\n\n"
            fs.writeFileSync('comment.txt', comment_body);

      - run: cat comment.txt

      - name: Comment
        uses: umanghome/create-or-update-comment@main
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          edit-mode: replace
          file: comment.txt

      - name: Close Issue
        if: github.event.issue.state == 'open'
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}