name: retracer_app

on:
  issues:
    types: [opened, edited]

env:
  INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  ParseCrashLog:
    if: github.event.label.name == 'crash'
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.issue.id }}
          reactions: eyes

      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: "stable"

      # prepare debug symbols and crash mini dump
      - name: PrepareSymbol
        id: prepare_symbol
        working-directory: retracer_app
        run: |
          dart pub get
          dart run retracer_app "${{ github.event.comment.body }}"

      - name: PrintInfo
        run: |
          echo "mini_dump_file: ${{ steps.prepare_symbol.outputs.mini_dump_file }}"
          echo "symbol_directory: ${{ steps.prepare_symbol.outputs.symbol_directory }}"

      - name: DumpCrashLog
        id: dump_crash_log
        run: |
          ./breakpad/linux/x86_64/minidump_stackwalk "${{ steps.prepare_symbol.outputs.mini_dump_file }}" "${{ steps.prepare_symbol.outputs.symbol_directory }}" > crash.log
          crash_log=$(cat crash.log)
          echo "::set-output name=crash_log::$crash_log"

#      - name: Find Comment
#        uses: peter-evans/find-comment@v2
#        id: fc
#        with:
#          issue-number: ${{ github.event.pull_request.number }}
#          comment-author: 'github-actions[bot]'
#          body-includes: Build output

      - name: PrintCrashLogToComment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            `${{ steps.prepare_symbol.outputs.mini_dump_file }}`
            
            ```
            ${{ steps.dump_crash_log.outputs.crash_log }}
            ```