name: retracer_app

on:
  issue_comment:

env:
  INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  ParseCrashLog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: "stable"

      # prepare debug symbols and crash mini dump
      - name: PrepareSymbol
        id: prepare_symbol
        working-directory: retracer_app
        run: |
          dart pub get
          dart run retracer_app "${{ github.event.comment.body }}"

      - name: PrintInfo
        run: |
          echo "mini_dump_file: ${{ steps.prepare_symbol.outputs.mini_dump_file }}"
          echo "symbol_directory: ${{ steps.prepare_symbol.outputs.symbol_directory }}"